<a href="https://colab.research.google.com/github/KrishmaPaudel/ML_learning/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df= sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X=df.drop("species",axis=1)
y=df['species']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn= KNeighborsClassifier(n_neighbors=5)

In [ ]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
model_knn.score(X_test, y_test)

0.98

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_svm= SVC(gamma='auto')

In [ ]:
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [ ]:
model_svm.score(X_test,y_test)

1.0

In [ ]:
#now let's use Grid Search CV

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier= GridSearchCV((model_svm), {
    "C": [1,10,20,30],
    "kernel": ['rbf', 'linear'],

}, cv=5, return_train_score= False)

In [ ]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00272713, 0.00205407, 0.00194564, 0.00261903, 0.0020021 ,
        0.00202165, 0.00176468, 0.00170207]),
 'std_fit_time': array([0.00125617, 0.00057551, 0.0002489 , 0.00083647, 0.00025988,
        0.00060856, 0.00011775, 0.0002584 ]),
 'mean_score_time': array([0.00151224, 0.0012856 , 0.0016973 , 0.0016448 , 0.00157452,
        0.001403  , 0.00125909, 0.00126495]),
 'std_score_time': array([1.38100504e-04, 5.71945052e-05, 5.14266720e-04, 3.70182521e-04,
        3.04723121e-04, 2.99695799e-04, 5.05157153e-05, 7.68053676e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
results= pd.DataFrame(classifier.cv_results_)

In [ ]:
results

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.002727      0.001256  ...        0.016330                1
1       0.002054      0.000576  ...        0.016330                1
2       0.001946      0.000249  ...        0.016330                1
3       0.002619      0.000836  ...        0.038873                4
4       0.002002      0.000260  ...        0.036515                5
5       0.002022      0.000609  ...        0.042164                6
6       0.001765      0.000118  ...        0.038873                7
7       0.001702      0.000258  ...        0.048990                7

[8 rows x 15 columns]

In [ ]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [ ]:
classifier1= GridSearchCV((model_knn), {
    "n_neighbors": [5,7,9,11,13],
    "weights": ['uniform', 'distance'],

}, cv=5, return_train_score= False)

In [ ]:
classifier1.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [5, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']})

In [ ]:
classifier1.cv_results_

{'mean_fit_time': array([0.00215669, 0.00156245, 0.00162878, 0.0016778 , 0.00156751,
        0.0015357 , 0.00150347, 0.00154519, 0.00211048, 0.0016993 ]),
 'std_fit_time': array([5.40656790e-04, 5.74636457e-05, 8.11078280e-05, 1.19413716e-04,
        4.48203086e-05, 4.60550152e-05, 6.89573140e-05, 4.56388215e-05,
        9.02189046e-04, 1.35205627e-04]),
 'mean_score_time': array([0.00337396, 0.00192151, 0.00239592, 0.00206342, 0.00238357,
        0.00171804, 0.00220928, 0.00173354, 0.00273666, 0.00204926]),
 'std_score_time': array([9.59783899e-04, 2.36689669e-04, 5.10350325e-05, 2.55351556e-04,
        8.87938906e-05, 4.48966937e-05, 5.21557413e-05, 6.39370887e-05,
        3.29549491e-04, 1.53195127e-04]),
 'param_n_neighbors': masked_array(data=[5, 5, 7, 7, 9, 9, 11, 11, 13, 13],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'n_neighbors': 5, 'weights': 'uniform'},
  {'n_neighbors': 5, 'weights': 'distance'},
  {'n_neighbors': 7, 'weights': 'uniform'},
  {'n_neighbors': 7, 'weights': 'distance'},
  {'n_neighbors': 9, 'weights': 'uniform'},
  {'n_neighbors': 9, 'weights': 'distance'},
  {'n_neighbors': 11, 'weights': 'uniform'},
  {'n_neighbors': 11, 'weights': 'distance'},
  {'n_neighbors': 13, 'weights': 'uniform'},
  {'n_neighbors': 13, 'weights': 'distance'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.93333333, 0.96666667]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.93333333, 0.9       , 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 1.        , 1.        , 0.96666667, 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.97333333, 0.96666667, 0.98      , 0.98      , 0.97333333,
        0.97333333, 0.98      , 0.98666667, 0.97333333, 0.98      ]),
 'std_test_score': array([0.02494438, 0.03651484, 0.01632993, 0.01632993, 0.02494438,
        0.02494438, 0.02666667, 0.01632993, 0.02494438, 0.01632993]),
 'rank_test_score': array([ 6, 10,  2,  2,  6,  6,  2,  1,  6,  2], dtype=int32)}

In [ ]:
results1= pd.DataFrame(classifier.cv_results_)

In [ ]:
results1[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [ ]:
results1

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.002727      0.001256  ...        0.016330                1
1       0.002054      0.000576  ...        0.016330                1
2       0.001946      0.000249  ...        0.016330                1
3       0.002619      0.000836  ...        0.038873                4
4       0.002002      0.000260  ...        0.036515                5
5       0.002022      0.000609  ...        0.042164                6
6       0.001765      0.000118  ...        0.038873                7
7       0.001702      0.000258  ...        0.048990                7

[8 rows x 15 columns]

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifier_r= RandomizedSearchCV((model_svm), {
    "C": [1,10,20,30],
    "kernel": ['rbf', 'linear'],

},n_iter=4, cv=5, return_train_score= False)

In [ ]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
classifier_r.cv_results_

{'mean_fit_time': array([0.00194893, 0.00165062, 0.00164294, 0.00190201]),
 'std_fit_time': array([4.73753005e-04, 3.13036967e-05, 5.02465105e-05, 5.41692712e-04]),
 'mean_score_time': array([0.00139189, 0.00131664, 0.0012403 , 0.00142827]),
 'std_score_time': array([2.49765146e-04, 1.26018471e-04, 1.23356215e-05, 2.01270790e-04]),
 'param_kernel': masked_array(data=['linear', 'rbf', 'rbf', 'linear'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[10, 10, 30, 20],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'C': 10},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'rbf', 'C': 30},
  {'kernel': 'linear', 'C': 20}],
 'split0_test_score': array([1.        , 0.96666667, 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667, 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1.]),
 'mean_test_score': array([0.97333333, 0.98      , 0.96      , 0.96666667]),
 'std_test_score': array([0.03887301, 0.01632993, 0.03887301, 0.0421637 ]),
 'rank_test_score': array([2, 1, 4, 3], dtype=int32)}

In [ ]:
results_r= pd.DataFrame(classifier_r.cv_results_)

In [ ]:
results_r

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.001949      0.000474  ...        0.038873                2
1       0.001651      0.000031  ...        0.016330                1
2       0.001643      0.000050  ...        0.038873                4
3       0.001902      0.000542  ...        0.042164                3

[4 rows x 15 columns]

In [ ]:
results_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10       linear         0.973333
1       10          rbf         0.980000
2       30          rbf         0.960000
3       20       linear         0.966667